### ISSUE TITLE
How Can I get Habpanel User Interface in Eclipse Smart Home?

### ISSUE THREAD

**Issue by amarpulli1994** [eclipse/smarthome-packaging-sample#10]
Hello,
I am trying to do add user interface to eclipse smart home. I am not able to get User Interface , while running eclipse smart home by using start.sh command.  Will get only paper UI . Please help me.
Thanks.

**Comment by kaikreuzer** [comment]
Duplicate of https://github.com/eclipse/smarthome-packaging-sample/issues/9.
