### ISSUE TITLE
 Where and how to create, configure and access sitemap, items and rules ...

### ISSUE THREAD

**Issue by kirantpatil** [eclipse/smarthome-packaging-sample#11]
Hi,

We did build as per instruction but  it has no "conf" folder.

Where and how to create, configure and access sitemap, items and rules  ... ?

Thanks.

**Comment by sjsf** [comment]
Please note that this minimal distribution does not contain any Xtext related bundles, therefore the mentioned files cannot be used.

You may use the PaperUI and/or OSGi console to maintain them. Sitemaps simply are not available, also no BasicUI/HABPanel.

**Comment by kaikreuzer** [comment]
See https://github.com/eclipse/smarthome-packaging-sample#limitations

**Comment by falmanna** [comment]
Hi @sjka @kaikreuzer 
Which dependency is causing this lack of support?

From my experience, I was trying to support sitemaps, but after resolving many dependencies, I was stuck at `org.xml.sax.ext`. I think it is related to Equinox framework.

**Comment by sjsf** [comment]
The only reason was to keep is as small as possible. There technically is nothing preventing you from installing all the model related bundles with all their Xtext/Xtend/EMF dependencies. That'll run equally fine on concierge. That's in fact what I am doing for myself.

If you're running on concierge, you'll need to add the mentioned package to the `org.osgi.framework.system.packages.extra` configuration. It come from the JRE, but the framework needs to be told explicitly to expose it as it is not within the `java.*` namespace.

**Comment by falmanna** [comment]
thanks @sjka , it resolved, 

For future, I like to mention that `org.eclipse.xtext` depends on `org.eclipse.equinox.common` and Equinox common has some dependencies to Equinox OSGi framework. To resolve these dependencies, there is a bundle`org.eclipse.equinox.supplement` that resolves most of them.

**Comment by maggu2810** [comment]
> For future, I like to mention that org.eclipse.xtext depends on org.eclipse.equinox.common and Equinox common has some dependencies to Equinox OSGi framework. To resolve these dependencies, there is a bundleorg.eclipse.equinox.supplement that resolves most of them.

Thanks, but we know.
I solved this dependency chain already at the time I created the Karaf features.

**Comment by falmanna** [comment]
It took me a while to resolve this one, I think writing it here will help others in future.

**Comment by maggu2810** [comment]
So, for reference you can have a look at the respective feature here: https://github.com/eclipse/smarthome/blob/77648eb/features/karaf/esh-tp/src/main/feature/feature.xml#L156

**Comment by falmanna** [comment]
Thanks @maggu2810, this would've saved me much time!
I am not that familiar with the concept of a `feature` yet, but it looks like it is for managing/providing dependencies for each feature?

**Comment by maggu2810** [comment]
Have a look here: https://karaf.apache.org/manual/latest/#_feature_and_resolver
