### ISSUE TITLE
missing license statement

### ISSUE THREAD

**Issue by jliang1010** [eclipse/smarthome-packaging-sample#19]
Is it possible to include a license statement in the project? Otherwise, it's unclear what assumption we can make to use this project.

**Comment by kaikreuzer** [comment]
Thanks for noticing that it is missing!
Clearly, we need to clarify the license, so I have created https://github.com/eclipse/smarthome-packaging-sample/pull/20.

**Comment by jliang1010** [comment]
Great! Thanks a lot.
