### ISSUE TITLE
System Configuration can not save

### ISSUE THREAD

**Issue by SilentTheseYears** [eclipse/smarthome-packaging-sample#21]
System Configuration  will rollback to init, when restart the smarthome.

**Comment by sjsf** [comment]
Correct. That's what the following line does:

https://github.com/eclipse/smarthome-packaging-sample/blob/3f613d743676630c82f789c0d39acb1c1b423bb8/distro/runtime/concierge/smarthome.xargs#L9

If you don't like it, just comment it out. Keep in mind, this is a _minimal sample_, not a ready-to-use solution.
