### ISSUE TITLE
Distribution is not running on compact 2 profile: logback-bundles (JORAN) requires javax.naming

### ISSUE THREAD

**Issue by JochenHiller** [eclipse/smarthome-packaging-sample#6]
When running the distro based on Concierge/Eclipse SmartHome on JavaSE 8 compact 2 profile, logback bundle does NOT start due to missing javax.naming.* classes (not include in compact 2).

To fix this, logback bundles needs to be changed that they consider javax.naming.* as optional, in MANIFEST.MF and also in code base. Maybe some configuration options in JORAN of logback does not work, but this seems to be not relevant for using that in an embedded environment.

I will create a bug to logback and provide a PR for that. Then we can update the distro to an updated logback version.

**Comment by kaikreuzer** [comment]
Maybe we could also include a different logging library? What about log4j2?

**Comment by JochenHiller** [comment]
Interesting idea: this would reverse the logging adapters, that slf4j API would rely on an log4j backend.
Just as a quick check: it seems that log4j2 is significant bigger (core-jar about 1.4 MB) compared to logback (304+471 kB)
But nevertheless should be considered as an option, will take that into account.
For more details see https://logging.apache.org/log4j/2.x/

**Comment by kaikreuzer** [comment]
> it seems that log4j2 is significant bigger 

That's not nice then - 1.4MB is indeed a lot, just for the logging...
The old log4j [isn't an option either](http://stackoverflow.com/questions/23907728/how-to-use-log4j-in-embedded-jdk-compact-1-2-3).

Shouldn't it simply be possible to use jul as a backend for slf4j? Then we wouldn't need ANY additional logging library.

**Comment by JochenHiller** [comment]
> Shouldn't it simply be possible to use jul as a backend for slf4j? Then we wouldn't need ANY additional logging library.

Also a good idea to be considered. Especially for constrained devices jul is available in compact 1 profile. The needed `slf4j-jdk14-<version>.jar` for bridging to jul needs about 8k which is charming.

Do you think that this would be accepted? I do not know jul in all details, but I expect that configuration for logging is not as comfortable as in logback. But we should at least give it a try to see how it looks like for configuration.

**Comment by kaikreuzer** [comment]
Hey, this package is not about comfort, it is about having a minimal distro, so jul would be IDEAL!

**Comment by JochenHiller** [comment]
OK will give it a try

**Comment by JochenHiller** [comment]
I gave java.util.logging (jul) a try, and it seems to be usable. Even if configuration is not so comfortable as in logback.
See sample logging output:

```
2017-01-29 14:27:07.338 [FINE   ] [org.eclipse.smarthome.config.dispatch.internal.ConfigDispatcher readConfigs] - Configuration folder '.../target/smarthome-packaging-sample-0.9.0-SNAPSHOT/conf/services' does not exist.
2017-01-29 14:27:07.466 [INFO   ] [org.jupnp.UpnpServiceImpl startup   ] - Starting UPnP service...
2017-01-29 14:27:07.509 [INFO   ] [org.jupnp.transport.impl.osgi.HttpServiceServletContainerAdapter registerServlet] - Registering UPnP callback servlet as /upnpcallback
2017-01-29 14:27:07.576 [FINE   ] [org.eclipse.smarthome.core.thing.internal.ChannelItemProvider$4 run] - Enabling channel item provider.
2017-01-29 14:27:07.643 [FINE   ] [org.eclipse.smarthome.io.transport.upnp.UpnpIOServiceImpl activate] - Starting UPnP IO service...
2017-01-29 14:27:07.668 [WARNING] [org.jupnp.QueueingThreadPoolExecutor addToQueue] - Thread pool 'upnp-main' exhausted, queueing tasks now.
2017-01-29 14:27:07.674 [FINE   ] [org.eclipse.smarthome.core.common.ThreadPoolManager modified] - Updated scheduled thread pool 'discovery' to size 3
```

There is one drawback: you can only configure ONE (1) file for output. So separation of all events into its own logfile `./userdata/logs/events-<id>.log` does not work out-of-the-box.
This could be solved by adding a second FileHandler class (just subclassing the standard class) and using its own path property. This class needs to be somewhere in `org.eclipse.smarthome.*` classes.
@kaikreuzer Do you think this should be done?

If we change this packaging sample to jul: shall we leave logback as a fallback in packaging, e.g. by commenting it out in distribution creation scripts? Or shall we completely get rid of it?
@kaikreuzer What do you think?

**Comment by kaikreuzer** [comment]
I think one log file is absolutely fine. As mentioned before, this is a minimal sample packaging - if somebody wants to build on this, he would probably anyhow go with some other logging library (depending on his solution).

To keep the sample package as simple as possible, I would remove all references to logback, i.e. not leave it in comments.
