### ISSUE TITLE
How to add habpanel as binding

### ISSUE THREAD

**Issue by kirantpatil** [eclipse/smarthome-packaging-sample#9]
Hi,

I would like to add [HABpanel](https://github.com/openhab/org.openhab.ui.habpanel) which is another UI apart from PaperUI, as binding to smarthome.

Please let us know how to do it ?

Thanks.

**Comment by kaikreuzer** [comment]
HABPanel is not part of ESH, so this is out of scope here, sorry.

**Comment by kirantpatil** [comment]
But, would like to know, how compile and use it with ESH ?

**Comment by sja** [comment]
These kind of questions may be better asked in https://community.openhab.org
